### ISSUE TITLE
A11y Issues

### ISSUE THREAD

**Issue by CalvinRodo** [DTS-STN/digital-dojo#2]
I ran some scans on the new digital-dojo site using aXe plugin to Chrome

The static site: 
![image](https://user-images.githubusercontent.com/87738/119878702-73dd9380-bef8-11eb-94cd-3e1d24ff1d6f.png)

The sign up form:

![image](https://user-images.githubusercontent.com/87738/119878791-8b1c8100-bef8-11eb-8dee-9c4b2e620cd2.png)

**Comment by britthurley** [comment]
Thanks @CalvinRodo ! Will action these :)

**Comment by britthurley** [comment]
We've resolved the majority of the issues, with some outstanding problems with our use of Hipporello forms. We intend to work with Hipporello to alleviate thiese issues, or pivot to a more accessible option come launch time!

Thanks for the help Cal!
